const cars = [
  {
    name: "Red Bull RB20",
    team: "Red Bull Racing",
    engine: "Honda RBPT",
    year: 2025,
    topSpeed: "378 km/h",
    power: "995hp",
    weight: "798 kg",
    imageList: "assets/RB20 1.webp",
    imageDetail: "assets/RB20 2.jpg",
    chassis: "Monocoque carbon fibre composite dengan struktur honeycomb.",
    wheelbase: "3610 mm",
    mainDrivers: "Max Verstappen NL , Yuki Tsunoda JP",
    championships: 8,
    acceleration: "0-100 km/h dalam 2.5 detik",
    aerodynamics: "Advanced downforce, enhanced DRS",
    suspension:
      "Double wishbone dengan push-rod yang mengaktifkan inboard springs dan torsion bars; Double wishbone dengan pull-rod layout, disesuaikan untuk efisiensi aliran udara dari diffuser",
    brakes: "Carbon-carbon discs and pads with improved cooling",
    transmission: "8-speed semi-automatic with quick shift",
    fuelCapacity: "110 kg",
    tireSupplier: "Pirelli",
    raceWins: 4,
    podiums: 9,
    points: 290,
    capacity: "16000cc",
    rpm: "15000RPM",
    valves: 24,
    trackWidth: "2000 mm",
    length: "5600 mm",
    width: "2000 mm",
    height: "950 mm",
    description:
      "Terkenal dengan strategi agresif, aerodinamika mutakhir, dan kecemerlangan Max Verstappen, Red Bull mendefinisikan ulang dominasi di era baru Formula 1.",
  },
  {
    name: "Red Bull RB19",
    team: "Red Bull Racing",
    engine: "Honda RBPT",
    year: 2024,
    topSpeed: "378 km/h",
    power: "1040-1080hp",
    weight: "798 kg",
    imageList: "assets/RB19 1.jpg",
    imageDetail: "assets/RB19 2.webp",
    chassis: "Monocoque carbon fibre composite dengan struktur honeycomb.",
    wheelbase: "3600 mm",
    mainDrivers: "Max Verstappen NL , Sergio Perez MX",
    championships: 8,
    acceleration: "0-100 km/h dalam 2.5 detik",
    aerodynamics: "High",
    suspension:
      "Double wishbone dengan push-rod yang mengaktifkan inboard springs dan torsion bars; Double wishbone dengan pull-rod layout, disesuaikan untuk efisiensi aliran udara dari diffuser",
    brakes: "Carbon-carbon discs and pads",
    transmission: "8-speed semi-automatic",
    fuelCapacity: "110 kg",
    tireSupplier: "Pirelli",
    raceWins: 21,
    podiums: 30,
    points: 589,
    capacity: "16000cc",
    rpm: "15000RPM",
    valves: 24,
    trackWidth: "2000 mm",
    length: "5600 mm",
    width: "2000 mm",
    height: "950 mm",
    description:
      "Terkenal dengan strategi agresif, aerodinamika mutakhir, dan kecemerlangan Max Verstappen, Red Bull mendefinisikan ulang dominasi di era baru Formula 1.",
  },
  {
    name: "Red Bull RB18",
    team: "Red Bull Racing",
    engine: "Honda RBPT",
    year: 2023,
    topSpeed: "378 km/h",
    power: "950~hp",
    weight: "798 kg",
    imageList: "assets/RB18 1.jpg",
    imageDetail: "assets/RB18 2.jpg",
    chassis: "Monocoque carbon fibre composite dengan struktur honeycomb.",
    wheelbase: "3600 mm",
    mainDrivers: "Max Verstappen NL , Sergio Perez MX",
    championships: 8,
    acceleration: "0-100 km/h dalam 2.6 detik",
    aerodynamics: "High",
    suspension:
      "Double wishbone dengan push-rod yang mengaktifkan inboard springs dan torsion bars; Double wishbone dengan pull-rod layout, disesuaikan untuk efisiensi aliran udara dari diffuser",
    brakes: "Carbon-carbon discs and pads",
    transmission: "8-speed semi-automatic",
    fuelCapacity: "110 kg",
    tireSupplier: "Pirelli",
    raceWins: 17,
    podiums: 28,
    points: 860,
    capacity: "16000cc",
    rpm: "15000RPM",
    valves: 24,
    trackWidth: "2000 mm",
    length: "5600 mm",
    width: "2000 mm",
    height: "960 mm",
    description:
      "Terkenal dengan strategi agresif, aerodinamika mutakhir, dan kecemerlangan Max Verstappen, Red Bull mendefinisikan ulang dominasi di era baru Formula 1.",
  },
  {
    name: "Ferrari SF-25",
    team: "Scuderia Ferrari",
    engine: "Ferrari",
    year: 2025,
    topSpeed: "378 km/h",
    power: "1000+hp",
    weight: "798 kg",
    imageList: "assets/SF25 1.jpg",
    imageDetail: "assets/SF25 2",
    chassis: "Monocoque carbon fibre composite dengan struktur honeycomb.",
    wheelbase: "3600 mm",
    mainDrivers: "Charles Lecrec MC , Lewis Hamilton UK",
    acceleration: "0-100 km/h dalam 2.6 detik",
    aerodynamics: "Medium-High",
    suspension:
      "Double wishbone dengan push-rod yang mengaktifkan inboard springs dan torsion bars; Double wishbone dengan pull-rod layout, disesuaikan untuk efisiensi aliran udara dari diffuser",
    brakes: "Carbon-carbon discs and pads",
    transmission: "8-speed semi-automatic",
    fuelCapacity: "110 kg",
    tireSupplier: "Pirelli",
    raceWins: 0,
    podiums: 5,
    points: 298,
    capacity: "16000cc",
    rpm: "15000RPM",
    valves: 24,
    trackWidth: "2000 mm",
    length: "5600 mm",
    width: "2000 mm",
    height: "960 mm",
    description:
      "Tim tertua dan paling ikonis di Formula 1, Ferrari mewujudkan hasrat, tradisi, dan pengejaran kecepatan tanpa henti, mewakili semangat balap Italia.",
  },
  {
    name: "Ferrari SF-24",
    team: "Scuderia Ferrari",
    engine: "Ferrari",
    year: 2024,
    topSpeed: "378 km/h",
    power: "1080hp",
    weight: "798 kg",
    imageList: "assets/SF24 1.jpg",
    imageDetail: "assets/SF24 2",
    chassis: "Monocoque carbon fibre composite dengan struktur honeycomb.",
    wheelbase: "3600 mm",
    mainDrivers: "Charles Lecrec MC , Carlos Sainz ES",
    acceleration: "0-100 km/h dalam 2.65 detik",
    aerodynamics: "Medium-High",
    suspension:
      "Double wishbone dengan push-rod yang mengaktifkan inboard springs dan torsion bars; Double wishbone dengan pull-rod layout, disesuaikan untuk efisiensi aliran udara dari diffuser",
    brakes: "Carbon-carbon discs and pads",
    transmission: "8-speed semi-automatic",
    fuelCapacity: "110 kg",
    tireSupplier: "Pirelli",
    raceWins: 5,
    podiums: 22,
    points: 652,
    capacity: "16000cc",
    rpm: "15000RPM",
    valves: 24,
    trackWidth: "2000 mm",
    length: "5600 mm",
    width: "2000 mm",
    height: "960 mm",
    description:
      "Tim tertua dan paling ikonis di Formula 1, Ferrari mewujudkan hasrat, tradisi, dan pengejaran kecepatan tanpa henti, mewakili semangat balap Italia.",
  },
  {
    name: "Ferrari SF-23",
    team: "Scuderia Ferrari",
    engine: "Ferrari",
    year: 2023,
    topSpeed: "378 km/h",
    power: "1010hp",
    weight: "798 kg",
    imageList: "assets/SF23 1.jpg",
    imageDetail: "assets/SF23 2.jpg",
    chassis: "Monocoque carbon fibre composite dengan struktur honeycomb.",
    wheelbase: "3600 mm",
    mainDrivers: "Charles Lecrec MC , Carlos Sainz ES",
    acceleration: "0-100 km/h dalam 2.68 detik",
    aerodynamics: "Medium",
    suspension:
      "Double wishbone dengan push-rod yang mengaktifkan inboard springs dan torsion bars; Double wishbone dengan pull-rod layout, disesuaikan untuk efisiensi aliran udara dari diffuser",
    brakes: "Carbon-carbon discs and pads",
    transmission: "8-speed semi-automatic",
    fuelCapacity: "110 kg",
    tireSupplier: "Pirelli",
    raceWins: 1,
    podiums: 9,
    points: 406,
    capacity: "16000cc",
    rpm: "15000RPM",
    valves: 24,
    trackWidth: "2000 mm",
    length: "5600 mm",
    width: "2000 mm",
    height: "960 mm",
    description:
      "Tim tertua dan paling ikonis di Formula 1, Ferrari mewujudkan hasrat, tradisi, dan pengejaran kecepatan tanpa henti, mewakili semangat balap Italia.",
  },
  {
    name: "Mercedes W16",
    team: "Mercedes-AMG Petronas",
    engine: "Mercedes",
    year: 2025,
    topSpeed: "378 km/h",
    power: "1000+hp",
    weight: "798 kg",
    imageList: "assets/W-16 1.webp",
    imageDetail: "assets/W-16 2.jpg",
    chassis: "Monocoque carbon fibre composite dengan struktur honeycomb.",
    wheelbase: "3600 mm",
    mainDrivers: "George Russel UK , Kimi Antonelli IT",
    acceleration: "0-100 km/h dalam 2.6 detik",
    aerodynamics: "Medium-High",
    suspension:
      "Double wishbone dengan push-rod yang mengaktifkan inboard springs dan torsion bars; Double wishbone dengan pull-rod layout, disesuaikan untuk efisiensi aliran udara dari diffuser",
    brakes: "Carbon-carbon discs and pads",
    transmission: "8-speed semi-automatic",
    fuelCapacity: "110 kg",
    tireSupplier: "Pirelli",
    raceWins: 2,
    podiums: 9,
    points: 325,
    capacity: "16000cc",
    rpm: "15000RPM",
    valves: 24,
    trackWidth: "2000 mm",
    length: "5600 mm",
    width: "2000 mm",
    height: "960 mm",
    description:
      "Kekuatan dominan di F1 modern, Mercedes dikenal karena keunggulan rekayasa, strategi presisi, dan rangkaian sukses era hibrida yang dipimpin oleh Lewis Hamilton dan Toto Wolff.",
  },
  {
    name: "Mercedes W15",
    team: "Mercedes-AMG Petronas",
    engine: "Mercedes",
    year: 2024,
    topSpeed: "378 km/h",
    power: "1080hp",
    weight: "798 kg",
    imageList: "assets/W-15 1.jpg",
    imageDetail: "assets/W-15 2.jpg",
    chassis: "Monocoque carbon fibre composite dengan struktur honeycomb.",
    wheelbase: "3600 mm",
    mainDrivers: "Lewis Hamilton UK , George Russel UK",
    acceleration: "0-100 km/h dalam 2.65 detik",
    aerodynamics: "Medium",
    suspension:
      "Double wishbone dengan push-rod yang mengaktifkan inboard springs dan torsion bars; Double wishbone dengan pull-rod layout, disesuaikan untuk efisiensi aliran udara dari diffuser",
    brakes: "Carbon-carbon discs and pads",
    transmission: "8-speed semi-automatic",
    fuelCapacity: "110 kg",
    tireSupplier: "Pirelli",
    raceWins: 4,
    podiums: 9,
    points: 468,
    capacity: "16000cc",
    rpm: "15000RPM",
    valves: 24,
    trackWidth: "2000 mm",
    length: "5600 mm",
    width: "2000 mm",
    height: "960 mm",
    description:
      "Kekuatan dominan di F1 modern, Mercedes dikenal karena keunggulan rekayasa, strategi presisi, dan rangkaian sukses era hibrida yang dipimpin oleh Lewis Hamilton dan Toto Wolff.",
  },
  {
    name: "Mercedes W14",
    team: "Mercedes-AMG Petronas",
    engine: "Mercedes",
    year: 2023,
    topSpeed: "378 km/h",
    power: "1000hp",
    weight: "798 kg",
    imageList: "assets/W-14 1",
    imageDetail: "assets/W-14 2.jpg",
    chassis: "Monocoque carbon fibre composite dengan struktur honeycomb.",
    wheelbase: "3600 mm",
    mainDrivers: "Lewis Hamilton UK , George Russel UK",
    acceleration: "0-100 km/h dalam 2.68 detik",
    aerodynamics: "Medium",
    suspension:
      "Double wishbone dengan push-rod yang mengaktifkan inboard springs dan torsion bars; Double wishbone dengan pull-rod layout, disesuaikan untuk efisiensi aliran udara dari diffuser",
    brakes: "Carbon-carbon discs and pads",
    transmission: "8-speed semi-automatic",
    fuelCapacity: "110 kg",
    tireSupplier: "Pirelli",
    raceWins: 0,
    podiums: 8,
    points: 409,
    capacity: "16000cc",
    rpm: "15000RPM",
    valves: 24,
    trackWidth: "2000 mm",
    length: "5600 mm",
    width: "2000 mm",
    height: "960 mm",
    description:
      "Kekuatan dominan di F1 modern, Mercedes dikenal karena keunggulan rekayasa, strategi presisi, dan rangkaian sukses era hibrida yang dipimpin oleh Lewis Hamilton dan Toto Wolff.",
  },
  {
    name: "McLaren MCL39",
    team: "McLaren",
    engine: "Mercedes",
    year: 2025,
    topSpeed: "378 km/h",
    power: "1000hp",
    weight: "798 kg",
    image: "assets/MCL39 1.jpg",
    imageDetail: "assets/MCL39 2.webp",
    chassis: "Monocoque carbon fibre composite dengan struktur honeycomb.",
    wheelbase: "3600 mm",
    mainDrivers: "Lando Norris UK , Oscar Piastri AU",
    acceleration: "0-100 km/h dalam 2.6 detik",
    aerodynamics: "Medium-High",
    suspension:
      "Double wishbone dengan push-rod yang mengaktifkan inboard springs dan torsion bars; Double wishbone dengan pull-rod layout, disesuaikan untuk efisiensi aliran udara dari diffuser",
    brakes: "Carbon-carbon discs and pads",
    transmission: "8-speed semi-automatic",
    fuelCapacity: "110 kg",
    tireSupplier: "Pirelli",
    raceWins: 12,
    podiums: 28,
    points: 650,
    capacity: "16000cc",
    rpm: "15000RPM",
    valves: 24,
    trackWidth: "2000 mm",
    length: "5600 mm",
    width: "2000 mm",
    height: "960 mm",
    description:
      "Salah satu tim paling bersejarah di F1, McLaren menggabungkan inovasi dan warisan balap dengan fokus pada talenta muda serta desain berperforma tinggi yang berakar pada tradisi Inggris.",
  },
  {
    name: "McLaren MCL38",
    team: "McLaren",
    engine: "Mercedes",
    year: 2024,
    topSpeed: "378 km/h",
    power: "1080hp",
    weight: "798 kg",
    imageList: "assets/MCL38 1.jpg",
    imageDetail: "assets/MCL38 2.jpg",
    chassis: "Monocoque carbon fibre composite dengan struktur honeycomb.",
    wheelbase: "3600 mm",
    mainDrivers: "Lando Norris UK , Oscar Piastri AU",
    acceleration: "0-100 km/h dalam 2.65 detik",
    aerodynamics: "Medium",
    suspension:
      "Double wishbone dengan push-rod yang mengaktifkan inboard springs dan torsion bars; Double wishbone dengan pull-rod layout, disesuaikan untuk efisiensi aliran udara dari diffuser",
    brakes: "Carbon-carbon discs and pads",
    transmission: "8-speed semi-automatic",
    fuelCapacity: "110 kg",
    tireSupplier: "Pirelli",
    raceWins: 4,
    podiums: 14,
    points: 666,
    capacity: "16000cc",
    rpm: "15000RPM",
    valves: 24,
    trackWidth: "2000 mm",
    length: "5600 mm",
    width: "2000 mm",
    height: "960 mm",
    description:
      "Salah satu tim paling bersejarah di F1, McLaren menggabungkan inovasi dan warisan balap dengan fokus pada talenta muda serta desain berperforma tinggi yang berakar pada tradisi Inggris.",
  },
  {
    name: "McLaren MCL60",
    team: "McLaren",
    engine: "Mercedes",
    year: 2023,
    topSpeed: "378 km/h",
    power: "1080hp",
    weight: "798 kg",
    imageList: "assets/MCL60 1.jpg",
    imageDetail: "assets/MCL60 2.webp",
    chassis: "Monocoque carbon fibre composite dengan struktur honeycomb.",
    wheelbase: "3600 mm",
    mainDrivers: "Lando Norris UK , Oscar Piastri AU",
    acceleration: "0-100 km/h dalam 2.68 detik",
    aerodynamics: "Medium",
    suspension:
      "Double wishbone dengan push-rod yang mengaktifkan inboard springs dan torsion bars; Double wishbone dengan pull-rod layout, disesuaikan untuk efisiensi aliran udara dari diffuser",
    brakes: "Carbon-carbon discs and pads",
    transmission: "8-speed semi-automatic",
    fuelCapacity: "110 kg",
    tireSupplier: "Pirelli",
    raceWins: 1,
    podiums: 9,
    points: 302,
    capacity: "16000cc",
    rpm: "15000RPM",
    valves: 24,
    trackWidth: "2000 mm",
    length: "5600 mm",
    width: "2000 mm",
    height: "960 mm",
    description:
      "Salah satu tim paling bersejarah di F1, McLaren menggabungkan inovasi dan warisan balap dengan fokus pada talenta muda serta desain berperforma tinggi yang berakar pada tradisi Inggris.",
  },
  {
    name: "Aston Martin AMR25",
    team: "Aston Martin",
    engine: "Mercedes",
    year: 2025,
    topSpeed: "378 km/h",
    power: "1000hp",
    weight: "798 kg",
    imageList: "assets/AMR25 1.webp",
    imageDetail: "assets/AMR25 2.jpg",
    chassis: "Monocoque carbon fibre composite dengan struktur honeycomb.",
    wheelbase: "3600 mm",
    mainDrivers: "Fernando Alonso ES , Lance Stroll CA",
    acceleration: "0-100 km/h dalam 2.6 detik",
    aerodynamics: "Medium-High",
    suspension:
      "Double wishbone dengan push-rod yang mengaktifkan inboard springs dan torsion bars; Double wishbone dengan pull-rod layout, disesuaikan untuk efisiensi aliran udara dari diffuser",
    brakes: "Carbon-carbon discs and pads",
    transmission: "8-speed semi-automatic",
    fuelCapacity: "110 kg",
    tireSupplier: "Pirelli",
    raceWins: 0,
    podiums: 0,
    points: 64,
    capacity: "16000cc",
    rpm: "15000RPM",
    valves: 24,
    trackWidth: "2000 mm",
    length: "5600 mm",
    width: "2000 mm",
    height: "960 mm",
    description:
      "Penantang bergaya yang berkembang pesat, memadukan identitas merek mewah dengan ambisi kompetitif, dipimpin oleh pengalaman Fernando Alonso dan visi untuk kemenangan di masa depan.",
  },
  {
    name: "Aston Martin AMR24",
    team: "Aston Martin",
    engine: "Mercedes",
    year: 2024,
    topSpeed: "378 km/h",
    power: "995+hp",
    weight: "798 kg",
    imageList: "assets/AMR24 1.jpg",
    imageDetail: "assets/AMR24 2.jpg",
    chassis: "Monocoque carbon fibre composite dengan struktur honeycomb.",
    wheelbase: "3600 mm",
    mainDrivers: "Fernando Alonso ES , Lance Stroll CA",
    acceleration: "0-100 km/h dalam 2.65 detik",
    aerodynamics: "Medium",
    suspension:
      "Double wishbone dengan push-rod yang mengaktifkan inboard springs dan torsion bars; Double wishbone dengan pull-rod layout, disesuaikan untuk efisiensi aliran udara dari diffuser",
    brakes: "Carbon-carbon discs and pads",
    transmission: "8-speed semi-automatic",
    fuelCapacity: "110 kg",
    tireSupplier: "Pirelli",
    raceWins: 1,
    podiums: 6,
    points: 94,
    capacity: "16000cc",
    rpm: "15000RPM",
    valves: 24,
    trackWidth: "2000 mm",
    length: "5600 mm",
    width: "2000 mm",
    height: "960 mm",
    description:
      "Penantang bergaya yang berkembang pesat, memadukan identitas merek mewah dengan ambisi kompetitif, dipimpin oleh pengalaman Fernando Alonso dan visi untuk kemenangan di masa depan.",
  },
  {
    name: "Aston Martin AMR23",
    team: "Aston Martin",
    engine: "Mercedes",
    year: 2023,
    topSpeed: "378 km/h",
    power: "1080hp",
    weight: "798 kg",
    imageList: "assets/AMR23 1.jpg",
    imageDetail: "assets/AMR23 2.jpg",
    chassis: "Monocoque carbon fibre composite dengan struktur honeycomb.",
    wheelbase: "3600 mm",
    mainDrivers: "Fernando Alonso ES , Lance Stroll CA",
    acceleration: "0-100 km/h dalam 2.68 detik",
    aerodynamics: "Medium",
    suspension:
      "Double wishbone dengan push-rod yang mengaktifkan inboard springs dan torsion bars; Double wishbone dengan pull-rod layout, disesuaikan untuk efisiensi aliran udara dari diffuser",
    brakes: "Carbon-carbon discs and pads",
    transmission: "8-speed semi-automatic",
    fuelCapacity: "110 kg",
    tireSupplier: "Pirelli",
    raceWins: 0,
    podiums: 8,
    points: 280,
    capacity: "16000cc",
    rpm: "15000RPM",
    valves: 24,
    trackWidth: "2000 mm",
    length: "5600 mm",
    width: "2000 mm",
    height: "960 mm",
    description:
      "Penantang bergaya yang berkembang pesat, memadukan identitas merek mewah dengan ambisi kompetitif, dipimpin oleh pengalaman Fernando Alonso dan visi untuk kemenangan di masa depan.",
  },
];

const drivers = [
  { name: "Max Verstappen", team: "Red Bull Racing", worldTitles: 3 },
  { name: "Sergio Pérez", team: "Red Bull Racing", worldTitles: 0 },
  { name: "Charles Leclerc", team: "Scuderia Ferrari", worldTitles: 0 },
  { name: "Carlos Sainz", team: "Scuderia Ferrari", worldTitles: 0 },
  { name: "George Russell", team: "Mercedes-AMG Petronas", worldTitles: 0 },
  { name: "Lewis Hamilton", team: "Mercedes-AMG Petronas", worldTitles: 7 },
  { name: "Lando Norris", team: "McLaren", worldTitles: 0 },
  { name: "Oscar Piastri", team: "McLaren", worldTitles: 0 },
  { name: "Fernando Alonso", team: "Aston Martin", worldTitles: 2 },
  { name: "Lance Stroll", team: "Aston Martin", worldTitles: 0 },
];

const quizQuestions = [
  {
    question:
      "Tim mana yang memenangkan Konstruktor Championship terbanyak dalam sejarah F1?",
    options: ["Ferrari", "Mercedes", "McLaren", "Red Bull"],
    answer: "Ferrari",
  },
  {
    question: "Siapa pembalap dengan gelar juara dunia terbanyak?",
    options: [
      "Lewis Hamilton",
      "Michael Schumacher",
      "Sebastian Vettel",
      "Ayrton Senna",
    ],
    answer: "Lewis Hamilton",
  },
  {
    question: "Sirkuit mana yang dikenal sebagai 'Temple of Speed'?",
    options: ["Monza", "Silverstone", "Spa-Francorchamps", "Monaco"],
    answer: "Monza",
  },
  {
    question: "Berapa poin yang didapat untuk posisi 1 di balapan F1 modern?",
    options: ["25", "18", "15", "10"],
    answer: "25",
  },
  {
    question: "Tim mana yang bermarkas di Brackley, Inggris?",
    options: ["Mercedes", "Ferrari", "Red Bull", "Williams"],
    answer: "Mercedes",
  },
  {
    question: "Ban mana yang paling cepat namun cepat aus?",
    options: ["Soft", "Medium", "Hard", "Intermediate"],
    answer: "Soft",
  },
  {
    question: "Apa kepanjangan DRS?",
    options: [
      "Drag Reduction System",
      "Downforce Regulation System",
      "Dual Rear Spoiler",
      "Dynamic Racing Setup",
    ],
    answer: "Drag Reduction System",
  },
  {
    question: "Siapa juara dunia F1 musim 2021?",
    options: [
      "Max Verstappen",
      "Lewis Hamilton",
      "Charles Leclerc",
      "Fernando Alonso",
    ],
    answer: "Max Verstappen",
  },
  {
    question: "Siapa pembalap yang dijuluki 'The Iceman'?",
    options: [
      "Kimi Räikkönen",
      "Valtteri Bottas",
      "Mika Häkkinen",
      "Fernando Alonso",
    ],
    answer: "Kimi Räikkönen",
  },
  {
    question: "Berapa jumlah balapan dalam kalender F1 2023?",
    options: ["23", "22", "24", "20"],
    answer: "23",
  },
  {
    question: "Sirkuit mana yang merupakan tuan rumah Grand Prix Monaco?",
    options: [
      "Circuit de Monaco",
      "Monte Carlo Circuit",
      "Monaco Street Circuit",
      "Circuit de la Condamine",
    ],
    answer: "Circuit de Monaco",
  },
  {
    question: "Siapa pendiri tim Ferrari F1?",
    options: [
      "Enzo Ferrari",
      "Luca di Montezemolo",
      "Sergio Marchionne",
      "Piero Ferrari",
    ],
    answer: "Enzo Ferrari",
  },
  {
    question: "Apa warna tradisional mobil balap Italia?",
    options: ["Rosso Corsa (Merah)", "Hijau", "Biru", "Kuning"],
    answer: "Rosso Corsa (Merah)",
  },
  {
    question:
      "Siapa pembalap F1 pertama yang memenangkan balapan dengan mobil turbo?",
    options: [
      "Jean-Pierre Jabouille",
      "Alain Prost",
      "Niki Lauda",
      "Gilles Villeneuve",
    ],
    answer: "Jean-Pierre Jabouille",
  },
  {
    question:
      "Apa nama sistem keselamatan yang diperkenalkan pada 2018 untuk melindungi kepala pembalap?",
    options: ["Halo", "Shield", "Aeroscreen", "Canopy"],
    answer: "Halo",
  },
  {
    question:
      "Siapa pembalap Indonesia pertama yang mengikuti sesi latihan bebas F1?",
    options: [
      "Rio Haryanto",
      "Sean Gelael",
      "Ananda Mikola",
      "Alexandra Asmasoebrata",
    ],
    answer: "Rio Haryanto",
  },
  {
    question: "Berapa jumlah silinder pada mesin F1 modern?",
    options: ["6", "8", "10", "12"],
    answer: "6",
  },
  {
    question: "Apa nama sistem pemulihan energi pada mobil F1 modern?",
    options: ["ERS", "KERS", "MGU", "Power Unit"],
    answer: "ERS",
  },
  {
    question: "Siapa pembalap yang memenangkan gelar juara dunia F1 pertama?",
    options: [
      "Giuseppe Farina",
      "Juan Manuel Fangio",
      "Alberto Ascari",
      "Stirling Moss",
    ],
    answer: "Giuseppe Farina",
  },
  {
    question:
      "Berapa kecepatan pit stop tercepat yang pernah dicatat dalam F1?",
    options: ["1.82 detik", "2.05 detik", "1.91 detik", "2.10 detik"],
    answer: "1.82 detik",
  },
  {
    question: "Sirkuit mana yang memiliki trek terpanjang di kalender F1?",
    options: [
      "Spa-Francorchamps",
      "Baku City Circuit",
      "Silverstone",
      "Circuit of the Americas",
    ],
    answer: "Spa-Francorchamps",
  },
  {
    question:
      "Apa nama teknologi yang memungkinkan mobil F1 menghasilkan downforce dari lantai mobil?",
    options: ["Ground Effect", "Diffuser", "Venturi Tunnels", "Floor Aero"],
    answer: "Ground Effect",
  },
  {
    question: "Siapa pembalap yang mendapat julukan 'El Matador'?",
    options: [
      "Fernando Alonso",
      "Carlos Sainz",
      "Pedro de la Rosa",
      "Marc Gene",
    ],
    answer: "Fernando Alonso",
  },
  {
    question:
      "Berapa kapasitas tangki bahan bakar maksimum pada mobil F1 modern?",
    options: ["110 kg", "100 kg", "120 kg", "105 kg"],
    answer: "110 kg",
  },
];
